# Generated by Django 5.1 on 2024-09-04 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_app', '0002_customuser_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile',
            field=models.ImageField(blank=True, null=True, upload_to='profile/'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='repassword',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
