# Generated by Django 5.1.1 on 2024-09-06 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_app', '0003_customuser_profile_customuser_repassword'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile',
            field=models.ImageField(blank=True, null=True, upload_to='static/profile/'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='static/resumes/'),
        ),
    ]
