# Generated by Django 5.1.1 on 2024-09-06 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_app', '0005_alter_customuser_profile_alter_customuser_resume'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='repassword',
        ),
        migrations.AddField(
            model_name='customuser',
            name='isEmployeer',
            field=models.BooleanField(default=False),
        ),
    ]
