# Generated by Django 5.1.1 on 2024-09-14 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_app', '0010_qualification_customuser_skills_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='pan_no',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
