# Generated by Django 5.1.3 on 2025-01-22 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobPosting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200, null=True)),
                ('company_address', models.CharField(max_length=200, null=True)),
                ('job_title', models.CharField(max_length=200, null=True)),
                ('job_type', models.CharField(choices=[('job_seeker', 'Job Seeker'), ('job_employer', 'Job Employer')], max_length=50, null=True)),
                ('experience_level', models.IntegerField(choices=[(1, 'Entry Level'), (2, 'Mid Level'), (3, 'Senior Level')], null=True)),
            ],
        ),
    ]
