# Generated by Django 5.1.3 on 2025-01-28 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposting',
            name='job_salary',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
