# Generated by Django 5.1.3 on 2025-01-28 11:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_jobposting_job_salary'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobposting',
            old_name='job_salary',
            new_name='max_salary',
        ),
        migrations.AddField(
            model_name='jobposting',
            name='min_salary',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='JobApply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(editable=False, max_length=200)),
                ('last_name', models.CharField(editable=False, max_length=200)),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('resume', models.FileField(blank=True, null=True, upload_to='jobapplied_resumes/')),
                ('phone_no', models.IntegerField(blank=True, null=True)),
                ('expected_salary', models.IntegerField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
