# Generated by Django 5.1.3 on 2025-01-22 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_jobposting'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposting',
            name='job_description',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='requirements',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='job_type',
            field=models.CharField(choices=[('full_time', 'Full Time'), ('part_time', 'Part_Time')], max_length=50, null=True),
        ),
    ]
