# Generated by Django 5.1.3 on 2025-01-28 11:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rename_job_salary_jobposting_max_salary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapply',
            name='job',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='accounts.jobposting'),
            preserve_default=False,
        ),
    ]
