# Generated by Django 5.1.3 on 2025-01-28 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_jobapply_job'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobapply',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='jobapply',
            name='last_name',
        ),
    ]
