# Generated by Django 5.1.3 on 2025-01-28 11:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_jobapply_first_name_remove_jobapply_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobposting',
            name='min_salary',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(10000)]),
        ),
    ]
