# Generated by Django 5.1.3 on 2025-01-30 05:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_jobposting_min_salary'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.IntegerField()),
                ('user_id', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='jobapply',
            name='job',
        ),
        migrations.AddField(
            model_name='jobapply',
            name='first_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='jobapply',
            name='job_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.jobposting'),
        ),
        migrations.AddField(
            model_name='jobapply',
            name='last_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='min_salary',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
