# Generated by Django 5.1.3 on 2025-01-30 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_customuser_latitude_customuser_longitude_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobapply',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='jobapply',
            name='location',
        ),
        migrations.RemoveField(
            model_name='jobapply',
            name='longitude',
        ),
        migrations.AlterField(
            model_name='jobapply',
            name='first_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='jobapply',
            name='last_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
