# Generated by Django 5.1.6 on 2025-02-20 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapply',
            name='status',
            field=models.CharField(choices=[('applied', 'Applied'), ('contacted', 'Contacted'), ('selected', 'Selected')], default='applied', max_length=20),
        ),
    ]
